import type { CardDetails } from '@/lib/types';

export const armor: CardDetails[] = [
  {
    type: 'equipment',
    name: 'Chainmail Armor',
    subtype: 'Armor',
    tier: 1,
    tierEnabled: true,
    thresholds: [7, 15],
    thresholdsEnabled: true,
    armor: 4,
    armorEnabled: true,
    text: `<p><strong><em>Heavy:</em></strong> -1 to Evasion</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Full Plate Armor',
    subtype: 'Armor',
    tier: 1,
    tierEnabled: true,
    thresholds: [8, 17],
    thresholdsEnabled: true,
    armor: 4,
    armorEnabled: true,
    text: `<p><strong><em>Very Heavy:</em></strong> -2 to Evasion; -1 to Agility</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Gambeson Armor',
    subtype: 'Armor',
    tier: 1,
    tierEnabled: true,
    thresholds: [5, 11],
    thresholdsEnabled: true,
    armor: 3,
    armorEnabled: true,
    text: `<p><strong><em>Flexible:</em></strong> +1 to Evasion</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Leather Armor',
    subtype: 'Armor',
    tier: 1,
    tierEnabled: true,
    thresholds: [6, 13],
    thresholdsEnabled: true,
    armor: 3,
    armorEnabled: true,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Elundrian Chain Armor',
    subtype: 'Armor',
    tier: 2,
    tierEnabled: true,
    thresholds: [9, 21],
    thresholdsEnabled: true,
    armor: 4,
    armorEnabled: true,
    text: `<p><strong><em>Warded:</em></strong> You reduce incoming magic damage by your Armor Score before applying it to your damage thresholds.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Harrowbone Armor',
    subtype: 'Armor',
    tier: 2,
    tierEnabled: true,
    thresholds: [9, 21],
    thresholdsEnabled: true,
    armor: 4,
    armorEnabled: true,
    text: `<p><strong><em>Resilient:</em></strong> Before you mark your last Armor Slot, roll a d6. On a result of 6, reduce the severity by one threshold without marking an Armor Slot.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Improved Chainmail Armor',
    subtype: 'Armor',
    tier: 2,
    tierEnabled: true,
    thresholds: [11, 24],
    thresholdsEnabled: true,
    armor: 5,
    armorEnabled: true,
    text: `<p><strong><em>Heavy:</em></strong> -1 to Evasion</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Improved Full Plate Armor',
    subtype: 'Armor',
    tier: 2,
    tierEnabled: true,
    thresholds: [13, 28],
    thresholdsEnabled: true,
    armor: 5,
    armorEnabled: true,
    text: `<p><strong><em>Very Heavy:</em></strong> -2 to Evasion; -1 to Agility</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Improved Gambeson Armor',
    subtype: 'Armor',
    tier: 2,
    tierEnabled: true,
    thresholds: [7, 16],
    thresholdsEnabled: true,
    armor: 4,
    armorEnabled: true,
    text: `<p><strong><em>Flexible:</em></strong> +1 to Evasion</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Improved Leather Armor',
    subtype: 'Armor',
    tier: 2,
    tierEnabled: true,
    thresholds: [9, 20],
    thresholdsEnabled: true,
    armor: 4,
    armorEnabled: true,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'IronTree Breastplate Armor',
    subtype: 'Armor',
    tier: 2,
    tierEnabled: true,
    thresholds: [9, 20],
    thresholdsEnabled: true,
    armor: 4,
    armorEnabled: true,
    text: `<p><strong><em>Reinforced:</em></strong> When you mark your last Armor Slot, increase your damage thresholds by +2 until you clear at least 1 Armor Slot.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Rosewild Armor',
    subtype: 'Armor',
    tier: 2,
    tierEnabled: true,
    thresholds: [11, 23],
    thresholdsEnabled: true,
    armor: 5,
    armorEnabled: true,
    text: `<p><strong><em>Hopeful:</em></strong> When you would spend a Hope, you can mark an Armor Slot instead.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Runetan Floating Armor',
    subtype: 'Armor',
    tier: 2,
    tierEnabled: true,
    thresholds: [9, 20],
    thresholdsEnabled: true,
    armor: 4,
    armorEnabled: true,
    text: `<p><strong><em>Shifting:</em></strong> When you are targeted for an attack, you can mark an Armor Slot to give the attack roll against you disadvantage.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Tyris Soft Armor',
    subtype: 'Armor',
    tier: 2,
    tierEnabled: true,
    thresholds: [8, 18],
    thresholdsEnabled: true,
    armor: 5,
    armorEnabled: true,
    text: `<p><strong><em>Quiet:</em></strong> You gain a +2 bonus to rolls you make to move silently.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Advanced Chainmail Armor',
    subtype: 'Armor',
    tier: 3,
    tierEnabled: true,
    thresholds: [13, 31],
    thresholdsEnabled: true,
    armor: 6,
    armorEnabled: true,
    text: `<p><strong><em>Heavy:</em></strong> -1 to Evasion</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Advanced Full Plate Armor',
    subtype: 'Armor',
    tier: 3,
    tierEnabled: true,
    thresholds: [15, 35],
    thresholdsEnabled: true,
    armor: 6,
    armorEnabled: true,
    text: `<p><strong><em>Very Heavy:</em></strong> -2 to Evasion; -1 to Agility</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Advanced Gambeson Armor',
    subtype: 'Armor',
    tier: 3,
    tierEnabled: true,
    thresholds: [9, 23],
    thresholdsEnabled: true,
    armor: 5,
    armorEnabled: true,
    text: `<p><strong><em>Flexible:</em></strong> +1 to Evasion</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Advanced Leather Armor',
    subtype: 'Armor',
    tier: 3,
    tierEnabled: true,
    thresholds: [11, 27],
    thresholdsEnabled: true,
    armor: 5,
    armorEnabled: true,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Bellamoi Fine Armor',
    subtype: 'Armor',
    tier: 3,
    tierEnabled: true,
    thresholds: [11, 27],
    thresholdsEnabled: true,
    armor: 5,
    armorEnabled: true,
    text: `<p><strong><em>Gilded:</em></strong> +1 to Presence</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Bladefare Armor',
    subtype: 'Armor',
    tier: 3,
    tierEnabled: true,
    thresholds: [16, 39],
    thresholdsEnabled: true,
    armor: 6,
    armorEnabled: true,
    text: `<p><strong><em>Physical:</em></strong> You can't mark an Armor Slot to reduce magic damage.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Dragonscale Armor',
    subtype: 'Armor',
    tier: 3,
    tierEnabled: true,
    thresholds: [11, 27],
    thresholdsEnabled: true,
    armor: 5,
    armorEnabled: true,
    text: `<p><strong><em>Impenetrable:</em></strong> Once per short rest, when you would mark your last Hit Point, you can instead mark a Stress.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: "Monett's Cloak",
    subtype: 'Armor',
    tier: 3,
    tierEnabled: true,
    thresholds: [16, 39],
    thresholdsEnabled: true,
    armor: 6,
    armorEnabled: true,
    text: `<p><strong><em>Magic:</em></strong> You can't mark an Armor Slot to reduce physical damage.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Runes of Fortification',
    subtype: 'Armor',
    tier: 3,
    tierEnabled: true,
    thresholds: [17, 43],
    thresholdsEnabled: true,
    armor: 6,
    armorEnabled: true,
    text: `<p><strong><em>Painful:</em></strong> Each time you mark an Armor Slot, you must mark a Stress.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Spiked Plate Armor',
    subtype: 'Armor',
    tier: 3,
    tierEnabled: true,
    thresholds: [10, 25],
    thresholdsEnabled: true,
    armor: 5,
    armorEnabled: true,
    text: `<p><strong><em>Sharp:</em></strong> On a successful attack against a target within Melee range, add a d4 to the damage roll.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Channeling Armor',
    subtype: 'Armor',
    tier: 4,
    tierEnabled: true,
    thresholds: [13, 36],
    thresholdsEnabled: true,
    armor: 5,
    armorEnabled: true,
    text: `<p><strong><em>Channeling:</em></strong> +1 to Spellcast Rolls</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Dunamis Silkchain',
    subtype: 'Armor',
    tier: 4,
    tierEnabled: true,
    thresholds: [13, 36],
    thresholdsEnabled: true,
    armor: 7,
    armorEnabled: true,
    text: `<p><strong><em>Timeslowing:</em></strong> Mark an Armor Slot to roll a d4 and add its result as a bonus to your Evasion against an incoming attack.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Emberwoven Armor',
    subtype: 'Armor',
    tier: 4,
    tierEnabled: true,
    thresholds: [13, 36],
    thresholdsEnabled: true,
    armor: 6,
    armorEnabled: true,
    text: `<p><strong><em>Burning:</em></strong> When an adversary attacks you within Melee range, they mark a Stress.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Full Fortified Armor',
    subtype: 'Armor',
    tier: 4,
    tierEnabled: true,
    thresholds: [15, 40],
    thresholdsEnabled: true,
    armor: 4,
    armorEnabled: true,
    text: `<p><strong><em>Fortified:</em></strong> When you mark an Armor Slot, you reduce the severity of an attack by two thresholds instead of one.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Legendary Chainmail Armor',
    subtype: 'Armor',
    tier: 4,
    tierEnabled: true,
    thresholds: [15, 40],
    thresholdsEnabled: true,
    armor: 7,
    armorEnabled: true,
    text: `<p><strong><em>Heavy:</em></strong> -1 to Evasion</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Legendary Full Plate Armor',
    subtype: 'Armor',
    tier: 4,
    tierEnabled: true,
    thresholds: [17, 44],
    thresholdsEnabled: true,
    armor: 7,
    armorEnabled: true,
    text: `<p><strong><em>Very Heavy:</em></strong> -2 to Evasion; -1 to Agility</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Legendary Gambeson Armor',
    subtype: 'Armor',
    tier: 4,
    tierEnabled: true,
    thresholds: [11, 32],
    thresholdsEnabled: true,
    armor: 6,
    armorEnabled: true,
    text: `<p><strong><em>Flexible:</em></strong> +1 to Evasion</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Legendary Leather Armor',
    subtype: 'Armor',
    tier: 4,
    tierEnabled: true,
    thresholds: [13, 36],
    thresholdsEnabled: true,
    armor: 6,
    armorEnabled: true,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Savior Chainmail',
    subtype: 'Armor',
    tier: 4,
    tierEnabled: true,
    thresholds: [18, 48],
    thresholdsEnabled: true,
    armor: 8,
    armorEnabled: true,
    text: `<p><strong><em>Difficult:</em></strong> -1 to all character traits and Evasion</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Veritas Opal Armor',
    subtype: 'Armor',
    tier: 4,
    tierEnabled: true,
    thresholds: [13, 36],
    thresholdsEnabled: true,
    armor: 6,
    armorEnabled: true,
    text: `<p><strong><em>Truthseeking:</em></strong> This armor glows when another creature within Close range tells a lie.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
];
