import type { CardDetails } from '@/lib/types';

export const consumables: CardDetails[] = [
  {
    type: 'equipment',
    name: 'Acidpaste',
    subtype: 'Consumable',
    text: `<p>This paste eats away walls and other surfaces in bright flashes.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Armor Stitcher',
    subtype: 'Consumable',
    text: `<p>You can use this stitcher to spend any number of Hope and clear that many Armor Slots.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Attune Potion',
    subtype: 'Consumable',
    text: `<p>You gain a +1 bonus to your next Instinct Roll.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Blinding Orb',
    subtype: 'Consumable',
    text: `<p>You can activate this orb to create a flash of bright light. All targets within Close range become Vulnerable until they mark HP.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Blood of the Yorgi',
    subtype: 'Consumable',
    text: `<p>You can drink this blood to disappear from where you are and immediately reappear at a point you can see within Very Far range.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Bolster Potion',
    subtype: 'Consumable',
    text: `<p>You gain a +1 bonus to your next Strength Roll.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Bonding Honey',
    subtype: 'Consumable',
    text: `<p>This honey can be used to glue two objects together permanently.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Bridge Seed',
    subtype: 'Consumable',
    text: `<p>Thick vines grow from your location to a point of your choice within Far range, allowing you to climb up or across them. The vines dissipate on your next rest.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Channelstone',
    subtype: 'Consumable',
    text: `<p>You can use this stone to take a spell or grimoire from your vault, use it once, and return it to your vault.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Charm Potion',
    subtype: 'Consumable',
    text: `<p>You gain a +1 bonus to your next Presence Roll.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Circle of the Void',
    subtype: 'Consumable',
    text: `<p>Mark a Stress to create a void that extends up to Far range. No magic can be cast inside the void, and creatures within the void are immune to magic damage.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Control Potion',
    subtype: 'Consumable',
    text: `<p>You gain a +1 bonus to your next Finesse Roll.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Death Tea',
    subtype: 'Consumable',
    text: `<p>After you drink this tea, you instantly kill your target when you critically succeed on an attack. If you don't critically succeed on an attack before your next long rest, you die.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Dragonbloom Tea',
    subtype: 'Consumable',
    text: `<p>You can drink this tea to unleash a fiery breath attack. Make an Instinct Roll against all adversaries in front of you within Close range. Targets you succeed against take 2d20 physical damage using your Proficiency.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Dripfang Poison',
    subtype: 'Consumable',
    text: `<p>A creature who consumes this poison takes 8d10 direct magic damage.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Enlighten Potion',
    subtype: 'Consumable',
    text: `<p>You gain a +1 bonus to your next Knowledge Roll.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Feast of Xuria',
    subtype: 'Consumable',
    text: `<p>You can eat this meal to clear all HP and Stress and gain 1d4 Hope.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Featherbone',
    subtype: 'Consumable',
    text: `<p>You can use this bone to control your falling speed for a number of minutes equal to your level.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Gill Salve',
    subtype: 'Consumable',
    text: `<p>You can apply this salve to your neck to breathe underwater for a number of minutes equal to your level.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Grindletooth Venom',
    subtype: 'Consumable',
    text: `<p>You can apply this venom to a weapon that deals physical damage to add a d6 to your next damage roll with that weapon.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Growing Potion',
    subtype: 'Consumable',
    text: `<p>You can drink this potion to double your size until you choose to drop this form or your next rest. While in this form, you have a +2 bonus to Strength and a +1 bonus to your Proficiency.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Health Potion',
    subtype: 'Consumable',
    text: `<p>Clear 1d4+1 HP.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: "Homet's Secret Potion",
    subtype: 'Consumable',
    text: `<p>After drinking this potion, the next successful attack you make critically succeeds.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Hopehold Flare',
    subtype: 'Consumable',
    text: `<p>When you use this flare, allies within Close range roll a d6 when they spend a Hope. On a result of 6, they gain the effect of that Hope without spending it. The flare lasts until the end of the scene.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'HORNET’S SECRET POTION',
    subtype: 'Consumable',
    text: `<p>After drinking this potion, the next successful attack you make critically succeeds.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Improved Arcane Shard',
    subtype: 'Consumable',
    text: `<p>You can make a Finesse Roll to throw this shard at a group of adversaries within Far range. Targets you succeed against take 2d20 magic damage.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Improved Grindletooth Venom',
    subtype: 'Consumable',
    text: `<p>You can apply this venom to a weapon that deals physical damage to add a d8 to your next damage roll with that weapon.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Jar of Lost Voices',
    subtype: 'Consumable',
    text: `<p>You can open this jar to release a deafening echo of voices for a number of minutes equal to your Instinct. Creatures within Far range unprepared for the sound take 6d8 magic damage.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Jumping Root',
    subtype: 'Consumable',
    text: `<p>Eat this root to leap up to Far range once without needing to roll.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Knowledge Stone',
    subtype: 'Consumable',
    text: `<p>If you die while holding this stone, an ally can take a card from your loadout to place in their loadout or vault. After they take this knowledge, the stone crumbles.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Major Arcane Shard',
    subtype: 'Consumable',
    text: `<p>You can make a Finesse Roll to throw this shard at a group of adversaries within Far range. Targets you succeed against take 4d20 magic damage.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Major Attune Potion',
    subtype: 'Consumable',
    text: `<p>You gain a +1 bonus to your Instinct until your next rest.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Major Bolster Potion',
    subtype: 'Consumable',
    text: `<p>You gain a +1 bonus to your Strength until your next rest.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Major Charm Potion',
    subtype: 'Consumable',
    text: `<p>You gain a +1 bonus to your Presence until your next rest.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Major Control Potion',
    subtype: 'Consumable',
    text: `<p>You gain a +1 bonus to your Finesse until your next rest.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Major Enlighten Potion',
    subtype: 'Consumable',
    text: `<p>You gain a +1 bonus to your Knowledge until your next rest.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Major Health Potion',
    subtype: 'Consumable',
    text: `<p>Clear 1d4+2 HP.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Major Stamina Potion',
    subtype: 'Consumable',
    text: `<p>Clear 1d4+2 Stress.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Major Stride Potion',
    subtype: 'Consumable',
    text: `<p>You gain a +1 bonus to your Agility until your next rest.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Minor Health Potion',
    subtype: 'Consumable',
    text: `<p>Clear 1d4 HP.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Minor Stamina Potion',
    subtype: 'Consumable',
    text: `<p>Clear 1d4 Stress.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Mirror of Marigold',
    subtype: 'Consumable',
    text: `<p>When you take damage, you can spend a Hope to negate that damage, after which the mirror shatters.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Morphing Clay',
    subtype: 'Consumable',
    text: `<p>You can spend a Hope to use this clay, altering your face enough to make you unrecognizable until your next rest.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Mythic Dust',
    subtype: 'Consumable',
    text: `<p>You can apply this dust to a weapon that deals magic damage to add a d12 to your next damage roll with that weapon.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Ogre Musk',
    subtype: 'Consumable',
    text: `<p>You can use this musk to prevent anyone from tracking you by mundane or magical means until your next rest.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Potion of Stability',
    subtype: 'Consumable',
    text: `<p>You can drink this potion to choose one additional downtime move.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Redthorn Saliva',
    subtype: 'Consumable',
    text: `<p>You can apply this saliva to a weapon that deals physical damage to add a d12 to your next damage roll with that weapon.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Replication Parchment',
    subtype: 'Consumable',
    text: `<p>By touching this piece of parchment to another, you can perfectly copy the second parchment's contents. Once used, this parchment becomes mundane paper.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Shrinking Potion',
    subtype: 'Consumable',
    text: `<p>You can drink this potion to halve your size until you choose to drop this form or your next rest. While in this form, you have a +2 bonus to Agility and a -1 penalty to your Proficiency.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Sleeping Sap',
    subtype: 'Consumable',
    text: `<p>You can drink this potion to fall asleep for a full night's rest. You clear all Stress upon waking.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Snap Powder',
    subtype: 'Consumable',
    text: `<p>Mark a Stress and clear a HP.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Stamina Potion',
    subtype: 'Consumable',
    text: `<p>Clear 1d4+1 Stress.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Stardrop',
    subtype: 'Consumable',
    text: `<p>You can use this stardrop to summon a hailstorm of comets that deals 8d20 physical damage to all targets within Very Far range.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Stride Potion',
    subtype: 'Consumable',
    text: `<p>You gain a +1 bonus to your next Agility Roll.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Sun Tree Sap',
    subtype: 'Consumable',
    text: `<p>Consume this sap to roll a d6. On a result of 5-6, clear 2 HP. On a result of 2-4, clear 3 Stress. On a result of 1, see through the veil of death and return changed, gaining one scar.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Sweet Moss',
    subtype: 'Consumable',
    text: `<p>You can consume this moss during a rest to clear 1d10 HP or 1d10 Stress.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Unstable Arcane Shard',
    subtype: 'Consumable',
    text: `<p>You can make a Finesse Roll to throw this shard at a group of adversaries within Far range. Targets you succeed against take 1d20 magic damage.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Varik Leaves',
    subtype: 'Consumable',
    text: `<p>You can eat these paired leaves to immediately gain 2 Hope.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Vial of Darksmoke',
    subtype: 'Consumable',
    text: `<p>When an adversary attacks you, use this vial and roll a number of d6s equal to your Agility. Add the highest result to your Evasion against the attack.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Vial of Moondrip',
    subtype: 'Consumable',
    text: `<p>When you drink the contents of this vial, you can see in total darkness until your next rest.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Wingsprout',
    subtype: 'Consumable',
    text: `<p>You gain magic wings that allow you to fly for a number of minutes equal to your level.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
];
