import type { CardDetails } from '@/lib/types';

export const items: CardDetails[] = [
  {
    type: 'equipment',
    name: 'Airblade Charm',
    subtype: 'Item',
    text: `<p>You can attach this charm to a weapon with a Melee range. Three times per rest, you can activate the charm and attack a target within Close range.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: "Alistair's Torch",
    subtype: 'Item',
    text: `<p>You can light this magic torch at will. The flame's light fills a much larger space than it should, enough to illuminate a cave bright as day.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Arcane Cloak',
    subtype: 'Item',
    text: `<p>A creature with a Spellcast trait wearing this cloak can adjust its color, texture, and size at will.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Arcane Prism',
    subtype: 'Item',
    text: `<p>Position this prism in a location of your choosing and activate it. All allies within Close range of it gain a +1 bonus to their Spellcast Rolls. While activated, the prism can't be moved. Once the prism is deactivated, it can't be activated again until your next long rest.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Attune Relic',
    subtype: 'Item',
    text: `<p>You gain a +1 bonus to your Instinct. You can only carry one relic.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Bag of Ficklesand',
    subtype: 'Item',
    text: `<p>You can convince this small bag of sand to be much heavier or lighter with a successful Presence Roll (10). Additionally, on a successful Finesse Roll (10), you can blow a bit of sand into a target’s face to make them temporarily Vulnerable.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Belt of Unity',
    subtype: 'Item',
    text: `<p>Once per session, you can spend 5 Hope to lead a Tag Team Roll with three PCs instead of two.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Bloodstone',
    subtype: 'Item',
    text: `<p>You can attach this stone to a weapon that doesn’t already have a feature. The weapon gains the following feature. Brutal: When you roll the maximum value on a damage die, roll an additional damage die.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Bolster Relic',
    subtype: 'Item',
    text: `<p>You gain a +1 bonus to your Strength. You can only carry one relic.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Box of Many Goods',
    subtype: 'Item',
    text: `<p>Once per long rest, you can open this small box and roll a d12. On a result of 1-6, it’s empty. On a result of 7-10, it contains one random common consumable. On a result of 11-12, it contains two random common consumables.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Calming Pendant',
    subtype: 'Item',
    text: `<p>When you would mark your last Stress, roll a d6. On a result of 5 or higher, don’t mark it.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Charging Quiver',
    subtype: 'Item',
    text: `<p>When you succeed on an attack with an arrow stored in this quiver, gain a bonus to the damage roll equal to your current tier.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Charm Relic',
    subtype: 'Item',
    text: `<p>You gain a +1 bonus to your Presence. You can only carry one relic.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Clay Companion',
    subtype: 'Item',
    text: `<p>When you sculpt this ball of clay into a clay animal companion, it behaves as that animal. For example, a clay spider can spin clay webs, while a clay bird can fly. The clay companion retains memory and identity across different shapes, but they can adopt new mannerisms with each form.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Companion Case',
    subtype: 'Item',
    text: `<p>This case can fit a small animal companion. While the companion is inside, the animal and case are immune to all damage and harmful effects.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Control Relic',
    subtype: 'Item',
    text: `<p>You gain a +1 bonus to your Finesse. You can only carry one relic.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Corrector Sprite',
    subtype: 'Item',
    text: `<p>This tiny sprite sits in the curve of your ear canal and whispers helpful advice during combat. Once per short rest, you can gain advantage on an attack roll.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Dual Flask',
    subtype: 'Item',
    text: `<p>This flask can hold two different liquids. You can swap between them by flipping a small switch on the flask’s side.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Elusive Amulet',
    subtype: 'Item',
    text: `<p>Once per long rest, you can activate this amulet to become Hidden until you move. While Hidden in this way, you remain unseen even if an adversary moves to where they would normally see you.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Empty Chest',
    subtype: 'Item',
    text: `<p>This magical chest appears empty. When you speak a specific trigger word or action and open the chest, you can see the items stored within it.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Enlighten Relic',
    subtype: 'Item',
    text: `<p>You gain a +1 bonus to your Knowledge. You can only carry one relic.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Fire Jar',
    subtype: 'Item',
    text: `<p>You can pour out the strange liquid contents of this jar to instantly produce fire. The contents regenerate when you take a long rest.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Flickerfly Pendant',
    subtype: 'Item',
    text: `<p>While you carry this pendant, your weapons with a Melee range that deal physical damage have a gossamer sheen and can attack targets within Very Close range.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Gecko Gloves',
    subtype: 'Item',
    text: `<p>You can climb up vertical surfaces and across ceilings.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Gem of Alacrity',
    subtype: 'Item',
    text: `<p>You can attach this gem to a weapon, allowing you to use your Agility when making an attack with that weapon.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Gem of Audacity',
    subtype: 'Item',
    text: `<p>You can attach this gem to a weapon, allowing you to use your Presence when making an attack with that weapon.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Gem of Insight',
    subtype: 'Item',
    text: `<p>You can attach this gem to a weapon, allowing you to use your Instinct when making an attack with that weapon.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Gem of Might',
    subtype: 'Item',
    text: `<p>You can attach this gem to a weapon, allowing you to use your Strength when making an attack with that weapon.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Gem of Precision',
    subtype: 'Item',
    text: `<p>You can attach this gem to a weapon, allowing you to use your Finesse when making an attack with that weapon.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Gem of Sagacity',
    subtype: 'Item',
    text: `<p>You can attach this gem to a weapon, allowing you to use your Knowledge when making an attack with that weapon.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Glamour Stone',
    subtype: 'Item',
    text: `<p>Activate this pebble-sized stone to memorize the appearance of someone you can see. Spend a Hope to magically recreate this guise on yourself as an illusion.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Glider',
    subtype: 'Item',
    text: `<p>While falling, you can mark a Stress to deploy this small parachute and glide safely to the ground.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Greatstone',
    subtype: 'Item',
    text: `<p>You can attach this stone to a weapon that doesn’t already have a feature. The weapon gains the following feature. Powerful: On a successful attack, roll an additional damage die and discard the lowest result.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Homing Compasses',
    subtype: 'Item',
    text: `<p>These two compasses point toward each other no matter how far apart they are.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Honing Relic',
    subtype: 'Item',
    text: `<p>You gain a +1 bonus to an Experience of your choice. You can only carry one relic.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Hopekeeper Locket',
    subtype: 'Item',
    text: `<p>During a long rest, if you have 6 Hope, you can spend a Hope to imbue this locket with your bountiful resolve. When you have 0 Hope, you can use the locket to immediately gain a Hope. The locket must be re‑imbued before it can be used this way again.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Infinite Bag',
    subtype: 'Item',
    text: `<p>When you store items in this bag, they are kept in a pocket dimension that never runs out of space. You can retrieve an item at any time.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Lakestrider Boots',
    subtype: 'Item',
    text: `<p>You can walk on the surface of water as if it were soft ground.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Lorekeeper',
    subtype: 'Item',
    text: `<p>You can store the name and details of up to three hostile creatures inside this book. You gain a +1 bonus to action rolls against those creatures.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Manacles',
    subtype: 'Item',
    text: `<p>This pair of locking cuffs comes with a key.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Minor Health Potion Recipe',
    subtype: 'Item',
    text: `<p>As a downtime move, you can use a vial of blood to craft a Minor Health Potion.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Minor Stamina Potion Recipe',
    subtype: 'Item',
    text: `<p>As a downtime move, you can use the bone of a creature to craft a Minor Stamina Potion.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Mythic Dust Recipe',
    subtype: 'Item',
    text: `<p>As a downtime move, you can use a handful of fine gold dust to craft Mythic Dust.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Paragon’s Chain',
    subtype: 'Item',
    text: `<p>As a downtime move, you can meditate on an ideal or principle you hold dear and focus your will into this chain. Once per long rest, you can spend a Hope to roll a d20 as your Hope Die for rolls that directly align with that principle.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Phoenix Feather',
    subtype: 'Item',
    text: `<p>If you have at least one Phoenix Feather on you when you fall unconscious, you gain a +1 bonus to the roll you make to determine whether you gain a scar.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Piercing Arrows',
    subtype: 'Item',
    text: `<p>Three times per rest when you succeed on an attack with one of these arrows, you can add your Proficiency to the damage roll.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Piper Whistle',
    subtype: 'Item',
    text: `<p>This handcrafted whistle has a distinctive sound. When you blow this whistle, its piercing tone can be heard within a 1-mile radius.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Portal Seed',
    subtype: 'Item',
    text: `<p>You can plant this seed in the ground to grow a portal in that spot. The portal is ready to use in 24 hours. You can use this portal to travel to any other location where you planted a portal seed. A portal can be destroyed by dealing any amount of Magic damage to it.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Premium Bedroll',
    subtype: 'Item',
    text: `<p>During downtime, you automatically clear a Stress.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Ring of Resistance',
    subtype: 'Item',
    text: `<p>Once per long rest, you can activate this ring after a successful attack against you to halve the damage.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Ring of Silence',
    subtype: 'Item',
    text: `<p>Spend a Hope to activate this ring. Your footsteps are silent until your next rest.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Ring of Unbreakable Resolve',
    subtype: 'Item',
    text: `<p>Once per session, when the GM spends a Fear, you can spend 4 Hope to cancel the effects of that spent Fear.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Shard of Memory',
    subtype: 'Item',
    text: `<p>Once per long rest, you can spend 2 Hope to recall a domain card from your vault instead of paying its Recall Cost.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Skeleton Key',
    subtype: 'Item',
    text: `<p>When you use this key to open a locked door, you gain advantage on the Finesse Roll.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Speaking Orbs',
    subtype: 'Item',
    text: `<p>This pair of orbs allows any creatures holding them to communicate with each other across any distance.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Stride Relic',
    subtype: 'Item',
    text: `<p>You gain a +1 bonus to your Agility. You can only carry one relic.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Suspended Rod',
    subtype: 'Item',
    text: `<p>This flat rod is inscribed with runes. When you activate the rod, it is immediately suspended in place. Until the rod is deactivated, it can't move, doesn't abide by the rules of gravity, and remains in place.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Valorstone',
    subtype: 'Item',
    text: `<p>You can attach this stone to armor that doesn't already have a feature. The armor gains the following feature. Resilient: Before you mark your last Armor Slot, roll a d6. On a result of 6, reduce the severity by one threshold without marking an Armor Slot.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Vial of Darksmoke Recipe',
    subtype: 'Item',
    text: `<p>As a downtime move, you can mark a Stress to craft a Vial of Darksmoke.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Woven Net',
    subtype: 'Item',
    text: `<p>You can make a Finesse Roll using this net to trap a small creature. A trapped target can break free with a successful Attack Roll (16).</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
];
