import type { CardDetails } from '@/lib/types';

export const weapons: CardDetails[] = [
  {
    type: 'equipment',
    name: 'Arcane Gauntlets',
    subtype: 'Primary Magical Weapon',
    tier: 1,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Melee | <strong>Damage:</strong> d10+3 magical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Battleaxe',
    subtype: 'Primary Physical Weapon',
    tier: 1,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Melee | <strong>Damage:</strong> d10+3 physical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Broadsword',
    subtype: 'Primary Physical Weapon',
    tier: 1,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Agility | <strong>Range:</strong> Melee | <strong>Damage:</strong> d8 physical</p>
<p><strong><em>Reliable:</em></strong> +1 to attack rolls</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Crossbow',
    subtype: 'Primary Physical Weapon',
    tier: 1,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Finesse | <strong>Range:</strong> Far | <strong>Damage:</strong> d6+1 physical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Cutlass',
    subtype: 'Primary Physical Weapon',
    tier: 1,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Presence | <strong>Range:</strong> Melee | <strong>Damage:</strong> d8+1 physical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Dagger',
    subtype: 'Primary Physical Weapon',
    tier: 1,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Finesse | <strong>Range:</strong> Melee | <strong>Damage:</strong> d8+1 physical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Dualstaff',
    subtype: 'Primary Magical Weapon',
    tier: 1,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Instinct | <strong>Range:</strong> Far | <strong>Damage:</strong> d6+3 magical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Glowing Rings',
    subtype: 'Primary Magical Weapon',
    tier: 1,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Agility | <strong>Range:</strong> Very Close | <strong>Damage:</strong> d10+2 magical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Grappler',
    subtype: 'Secondary Physical Weapon',
    tier: 1,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Finesse | <strong>Range:</strong> Close | <strong>Damage:</strong> d6 physical</p>
<p><strong><em>Hooked:</em></strong> On a successful attack, you can pull the target into Melee range.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Greatstaff',
    subtype: 'Primary Magical Weapon',
    tier: 1,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Knowledge | <strong>Range:</strong> Very Far | <strong>Damage:</strong> d6 magical</p>
<p><strong><em>Powerful:</em></strong> On a successful attack, roll an additional damage die and discard the lowest result.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Greatsword',
    subtype: 'Primary Physical Weapon',
    tier: 1,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Melee | <strong>Damage:</strong> d10+3 physical</p>
<p><strong><em>Massive:</em></strong> -1 to Evasion; on a successful attack, roll an additional damage die and discard the lowest result.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Halberd',
    subtype: 'Primary Physical Weapon',
    tier: 1,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Very Close | <strong>Damage:</strong> d10+2 physical</p>
<p><strong><em>Cumbersome:</em></strong> -1 to Finesse</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Hallowed Axe',
    subtype: 'Primary Magical Weapon',
    tier: 1,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Melee | <strong>Damage:</strong> d8+1 magical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Hand Crossbow',
    subtype: 'Secondary Physical Weapon',
    tier: 1,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Finesse | <strong>Range:</strong> Far | <strong>Damage:</strong> d6+1 physical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Hand Runes',
    subtype: 'Primary Magical Weapon',
    tier: 1,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Instinct | <strong>Range:</strong> Very Close | <strong>Damage:</strong> d10 magical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Longbow',
    subtype: 'Primary Physical Weapon',
    tier: 1,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Agility | <strong>Range:</strong> Very Far | <strong>Damage:</strong> d8+3 physical</p>
<p><strong><em>Cumbersome:</em></strong> -1 to Finesse</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Longsword',
    subtype: 'Primary Physical Weapon',
    tier: 1,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Agility | <strong>Range:</strong> Melee | <strong>Damage:</strong> d10+3 physical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Mace',
    subtype: 'Primary Physical Weapon',
    tier: 1,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Melee | <strong>Damage:</strong> d8+1 physical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Quarterstaff',
    subtype: 'Primary Physical Weapon',
    tier: 1,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Instinct | <strong>Range:</strong> Melee | <strong>Damage:</strong> d10+3 physical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Rapier',
    subtype: 'Primary Physical Weapon',
    tier: 1,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Presence | <strong>Range:</strong> Melee | <strong>Damage:</strong> d8 physical</p>
<p><strong><em>Quick:</em></strong> When you make an attack, you can mark a Stress to target another creature within range.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Returning Blade',
    subtype: 'Primary Magical Weapon',
    tier: 1,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Finesse | <strong>Range:</strong> Close | <strong>Damage:</strong> d8 magical</p>
<p><strong><em>Returning:</em></strong> When this weapon is thrown within its range, it appears in your hand immediately after the attack.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Round Shield',
    subtype: 'Secondary Physical Weapon',
    tier: 1,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Melee | <strong>Damage:</strong> d4 physical</p>
<p><strong><em>Protective:</em></strong> +1 to Armor Score</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Scepter',
    subtype: 'Primary Magical Weapon',
    tier: 1,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Presence | <strong>Range:</strong> Far | <strong>Damage:</strong> d6 magical</p>
<p><strong><em>Versatile:</em></strong> This weapon can also be used with these statistics—Presence, Melee, d8.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Shortbow',
    subtype: 'Primary Physical Weapon',
    tier: 1,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Agility | <strong>Range:</strong> Far | <strong>Damage:</strong> d6+3 physical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Shortstaff',
    subtype: 'Primary Magical Weapon',
    tier: 1,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Instinct | <strong>Range:</strong> Close | <strong>Damage:</strong> d8+1 magical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Shortsword',
    subtype: 'Secondary Physical Weapon',
    tier: 1,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Agility | <strong>Range:</strong> Melee | <strong>Damage:</strong> d8 physical</p>
<p><strong><em>Paired:</em></strong> +2 to primary weapon damage to targets within Melee range</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Small Dagger',
    subtype: 'Secondary Physical Weapon',
    tier: 1,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Finesse | <strong>Range:</strong> Melee | <strong>Damage:</strong> d8 physical</p>
<p><strong><em>Paired:</em></strong> +2 to primary weapon damage to targets within Melee range</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Spear',
    subtype: 'Primary Physical Weapon',
    tier: 1,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Finesse | <strong>Range:</strong> Very Close | <strong>Damage:</strong> d8+3 physical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Tower Shield',
    subtype: 'Secondary Physical Weapon',
    tier: 1,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Melee | <strong>Damage:</strong> d6 physical</p>
<p><strong><em>Barrier:</em></strong> +2 to Armor Score; -1 to Evasion</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Wand',
    subtype: 'Primary Magical Weapon',
    tier: 1,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Knowledge | <strong>Range:</strong> Far | <strong>Damage:</strong> d6+1 magical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Warhammer',
    subtype: 'Primary Physical Weapon',
    tier: 1,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Melee | <strong>Damage:</strong> d12+3 physical</p>
<p><strong><em>Heavy:</em></strong> -1 to Evasion</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Whip',
    subtype: 'Secondary Physical Weapon',
    tier: 1,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Presence | <strong>Range:</strong> Very Close | <strong>Damage:</strong> d6 physical</p>
<p><strong><em>Startling:</em></strong> Mark a Stress to crack the whip and force all adversaries within Melee range back to Close range.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Bladed Whip',
    subtype: 'Primary Physical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Agility | <strong>Range:</strong> Very Close | <strong>Damage:</strong> d8+3 physical</p>
<p><strong><em>Quick:</em></strong> When you make an attack, you can mark a Stress to target another creature within range.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Blunderbuss',
    subtype: 'Primary Physical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Finesse | <strong>Range:</strong> Close | <strong>Damage:</strong> d8+6 physical</p>
<p><strong><em>Reloading:</em></strong> After you make an attack, roll a d6. On a result of 1, you must mark a Stress to reload this weapon before you can fire it again.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Casting Sword',
    subtype: 'Primary Magical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Melee | <strong>Damage:</strong> d10+4 magical</p>
<p><strong><em>Versatile:</em></strong> This weapon can also be used with these statistics—Knowledge, Far, d6+3.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Devouring Dagger',
    subtype: 'Primary Magical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Finesse | <strong>Range:</strong> Melee | <strong>Damage:</strong> d8+4 magical</p>
<p><strong><em>Scary:</em></strong> On a successful attack, the target must mark a Stress.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Ego Blade',
    subtype: 'Primary Magical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Agility | <strong>Range:</strong> Melee | <strong>Damage:</strong> d12+4 magical</p>
<p><strong><em>Pompous:</em></strong> You must have a Presence of 0 or lower to use this weapon.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Elder Bow',
    subtype: 'Primary Magical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Instinct | <strong>Range:</strong> Far | <strong>Damage:</strong> d6+4 magical</p>
<p><strong><em>Powerful:</em></strong> On a successful attack, roll an additional damage die and discard the lowest result.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Finehair Bow',
    subtype: 'Primary Physical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Agility | <strong>Range:</strong> Very Far | <strong>Damage:</strong> d6+5 physical</p>
<p><strong><em>Reliable:</em></strong> +1 to attack rolls</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Gilded Falchion',
    subtype: 'Primary Physical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Melee | <strong>Damage:</strong> d10+4 physical</p>
<p><strong><em>Powerful:</em></strong> On a successful attack, roll an additional damage die and discard the lowest result.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Greatbow',
    subtype: 'Primary Physical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Far | <strong>Damage:</strong> d6+6 physical</p>
<p><strong><em>Powerful:</em></strong> On a successful attack, roll an additional damage die and discard the lowest result.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Hammer of Exota',
    subtype: 'Primary Magical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Instinct | <strong>Range:</strong> Melee | <strong>Damage:</strong> d8+6 magical</p>
<p><strong><em>Eruptive:</em></strong> On a successful attack against a target within Melee range, all other adversaries within Very Close range must succeed on a reaction roll (14) or take half damage.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Improved Arcane Gauntlets',
    subtype: 'Primary Magical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Melee | <strong>Damage:</strong> d10+6 magical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Improved Battleaxe',
    subtype: 'Primary Physical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Melee | <strong>Damage:</strong> d10+6 physical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Improved Broadsword',
    subtype: 'Primary Physical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Agility | <strong>Range:</strong> Melee | <strong>Damage:</strong> d8+3 physical</p>
<p><strong><em>Reliable:</em></strong> +1 to attack rolls</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Improved Crossbow',
    subtype: 'Primary Physical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Finesse | <strong>Range:</strong> Far | <strong>Damage:</strong> d6+4 physical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Improved Cutlass',
    subtype: 'Primary Physical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Presence | <strong>Range:</strong> Melee | <strong>Damage:</strong> d8+4 physical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Improved Dagger',
    subtype: 'Primary Physical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Finesse | <strong>Range:</strong> Melee | <strong>Damage:</strong> d8+4 physical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Improved Dualstaff',
    subtype: 'Primary Magical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Instinct | <strong>Range:</strong> Far | <strong>Damage:</strong> d6+6 magical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Improved Glowing Rings',
    subtype: 'Primary Magical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Agility | <strong>Range:</strong> Very Close | <strong>Damage:</strong> d10+5 magical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Improved Grappler',
    subtype: 'Secondary Physical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Finesse | <strong>Range:</strong> Close | <strong>Damage:</strong> d6+2 physical</p>
<p><strong><em>Hooked:</em></strong> On a successful attack, you can pull the target into Melee range.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Improved Greatstaff',
    subtype: 'Primary Magical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Knowledge | <strong>Range:</strong> Very Far | <strong>Damage:</strong> d6+3 magical</p>
<p><strong><em>Powerful:</em></strong> On a successful attack, roll an additional damage die and discard the lowest result.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Improved Greatsword',
    subtype: 'Primary Physical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Melee | <strong>Damage:</strong> d10+6 physical</p>
<p><strong><em>Massive:</em></strong> -1 to Evasion; on a successful attack, roll an additional damage die and discard the lowest result.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Improved Halberd',
    subtype: 'Primary Physical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Very Close | <strong>Damage:</strong> d10+5 physical</p>
<p><strong><em>Cumbersome:</em></strong> -1 to Finesse</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Improved Hallowed Axe',
    subtype: 'Primary Magical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Melee | <strong>Damage:</strong> d8+4 magical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Improved Hand Crossbow',
    subtype: 'Secondary Physical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Finesse | <strong>Range:</strong> Far | <strong>Damage:</strong> d6+3 physical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Improved Hand Runes',
    subtype: 'Primary Magical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Instinct | <strong>Range:</strong> Very Close | <strong>Damage:</strong> d10+3 magical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Improved Longbow',
    subtype: 'Primary Physical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Agility | <strong>Range:</strong> Very Far | <strong>Damage:</strong> d8+6 physical</p>
<p><strong><em>Cumbersome:</em></strong> -1 to Finesse</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Improved Longsword',
    subtype: 'Primary Physical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Agility | <strong>Range:</strong> Melee | <strong>Damage:</strong> d10+6 physical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Improved Mace',
    subtype: 'Primary Physical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Melee | <strong>Damage:</strong> d8+4 physical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Improved Quarterstaff',
    subtype: 'Primary Physical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Instinct | <strong>Range:</strong> Melee | <strong>Damage:</strong> d10+6 physical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Improved Rapier',
    subtype: 'Primary Physical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Presence | <strong>Range:</strong> Melee | <strong>Damage:</strong> d8+3 physical</p>
<p><strong><em>Quick:</em></strong> When you make an attack, you can mark a Stress to target another creature within range.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Improved Returning Blade',
    subtype: 'Primary Magical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Finesse | <strong>Range:</strong> Close | <strong>Damage:</strong> d8+3 magical</p>
<p><strong><em>Returning:</em></strong> When this weapon is thrown within its range, it appears in your hand immediately after the attack.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Improved Round Shield',
    subtype: 'Secondary Physical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Melee | <strong>Damage:</strong> d4+2 physical</p>
<p><strong><em>Protective:</em></strong> +2 to Armor Score</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Improved Scepter',
    subtype: 'Primary Magical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Presence | <strong>Range:</strong> Far | <strong>Damage:</strong> d6+3 magical</p>
<p><strong><em>Versatile:</em></strong> This weapon can also be used with these statistics—Presence, Melee, d8+3.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Improved Shortbow',
    subtype: 'Primary Physical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Agility | <strong>Range:</strong> Far | <strong>Damage:</strong> d6+6 physical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Improved Shortstaff',
    subtype: 'Primary Magical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Instinct | <strong>Range:</strong> Close | <strong>Damage:</strong> d8+4 magical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Improved Shortsword',
    subtype: 'Secondary Physical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Agility | <strong>Range:</strong> Melee | <strong>Damage:</strong> d8+2 physical</p>
<p><strong><em>Paired:</em></strong> +3 to primary weapon damage to targets within Melee range</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Improved Small Dagger',
    subtype: 'Secondary Physical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Finesse | <strong>Range:</strong> Melee | <strong>Damage:</strong> d8+2 physical</p>
<p><strong><em>Paired:</em></strong> +3 to primary weapon damage to targets within Melee range</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Improved Spear',
    subtype: 'Primary Physical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Finesse | <strong>Range:</strong> Very Close | <strong>Damage:</strong> d8+6 physical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Improved Tower Shield',
    subtype: 'Secondary Physical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Melee | <strong>Damage:</strong> d6+2 physical</p>
<p><strong><em>Barrier:</em></strong> +3 to Armor Score; -1 to Evasion</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Improved Wand',
    subtype: 'Primary Magical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Knowledge | <strong>Range:</strong> Far | <strong>Damage:</strong> d6+4 magical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Improved Warhammer',
    subtype: 'Primary Physical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Melee | <strong>Damage:</strong> d12+6 physical</p>
<p><strong><em>Heavy:</em></strong> -1 to Evasion</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Improved Whip',
    subtype: 'Secondary Physical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Presence | <strong>Range:</strong> Very Close | <strong>Damage:</strong> d6+2 physical</p>
<p><strong><em>Startling:</em></strong> Mark a Stress to crack the whip and force all adversaries within Melee range back to Close range.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: "Keeper's Staff",
    subtype: 'Primary Magical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Knowledge | <strong>Range:</strong> Far | <strong>Damage:</strong> d6+4 magical</p>
<p><strong><em>Reliable:</em></strong> +1 to attack rolls</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Knuckle Blades',
    subtype: 'Primary Physical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Melee | <strong>Damage:</strong> d10+6 physical</p>
<p><strong><em>Brutal:</em></strong> When you roll the maximum value on a damage die, roll an additional damage die.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Parrying Dagger',
    subtype: 'Secondary Physical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Finesse | <strong>Range:</strong> Melee | <strong>Damage:</strong> d6+2 physical</p>
<p><strong><em>Parry:</em></strong> When you are attacked, roll this weapon's damage dice. If any of the attacker's damage dice rolled the same value as your dice, the matching results are discarded from the attacker's damage dice before the damage you take is totaled.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Returning Axe',
    subtype: 'Secondary Physical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Agility | <strong>Range:</strong> Close | <strong>Damage:</strong> d6+4 physical</p>
<p><strong><em>Returning:</em></strong> When this weapon is thrown within its range, it appears in your hand immediately after the attack.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Scepter of Elias',
    subtype: 'Primary Magical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Presence | <strong>Range:</strong> Far | <strong>Damage:</strong> d6+3 magical</p>
<p><strong><em>Invigorating:</em></strong> On a successful attack, roll a d4. On a result of 4, clear a Stress.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Spiked Shield',
    subtype: 'Secondary Physical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Melee | <strong>Damage:</strong> d6+2 physical</p>
<p><strong><em>Double Duty:</em></strong> +1 to Armor Score; +1 to primary weapon damage within Melee range</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Steelforged Halberd',
    subtype: 'Primary Physical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Very Close | <strong>Damage:</strong> d8+4 physical</p>
<p><strong><em>Scary:</em></strong> On a successful attack, the target must mark a Stress.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Urok Broadsword',
    subtype: 'Primary Physical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Finesse | <strong>Range:</strong> Melee | <strong>Damage:</strong> d8+3 physical</p>
<p><strong><em>Deadly:</em></strong> When you deal Severe damage, the target must mark an additional HP.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Wand of Enthrallment',
    subtype: 'Primary Magical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Presence | <strong>Range:</strong> Far | <strong>Damage:</strong> d6+4 magical</p>
<p><strong><em>Persuasive:</em></strong> Before you make a Presence Roll, you can mark a Stress to gain a +2 bonus to the result.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'War Scythe',
    subtype: 'Primary Physical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Finesse | <strong>Range:</strong> Very Close | <strong>Damage:</strong> d8+5 physical</p>
<p><strong><em>Reliable:</em></strong> +1 to attack rolls</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Yutari Bloodbow',
    subtype: 'Primary Magical Weapon',
    tier: 2,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Finesse | <strong>Range:</strong> Far | <strong>Damage:</strong> d6+4 magical</p>
<p><strong><em>Brutal:</em></strong> When you roll the maximum value on a damage die, roll an additional damage die.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Advanced Arcane Gauntlets',
    subtype: 'Primary Magical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Melee | <strong>Damage:</strong> d10+9 magical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Advanced Battleaxe',
    subtype: 'Primary Physical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Melee | <strong>Damage:</strong> d10+9 physical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Advanced Broadsword',
    subtype: 'Primary Physical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Agility | <strong>Range:</strong> Melee | <strong>Damage:</strong> d8+6 physical</p>
<p><strong><em>Reliable:</em></strong> +1 to attack rolls</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Advanced Crossbow',
    subtype: 'Primary Physical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Finesse | <strong>Range:</strong> Far | <strong>Damage:</strong> d6+7 physical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Advanced Cutlass',
    subtype: 'Primary Physical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Presence | <strong>Range:</strong> Melee | <strong>Damage:</strong> d8+7 physical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Advanced Dagger',
    subtype: 'Primary Physical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Finesse | <strong>Range:</strong> Melee | <strong>Damage:</strong> d8+7 physical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Advanced Dualstaff',
    subtype: 'Primary Magical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Instinct | <strong>Range:</strong> Far | <strong>Damage:</strong> d6+9 magical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Advanced Glowing Rings',
    subtype: 'Primary Magical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Agility | <strong>Range:</strong> Very Close | <strong>Damage:</strong> d10+8 magical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Advanced Grappler',
    subtype: 'Secondary Physical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Finesse | <strong>Range:</strong> Close | <strong>Damage:</strong> d6+4 physical</p>
<p><strong><em>Hooked:</em></strong> On a successful attack, you can pull the target into Melee range.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Advanced Greatstaff',
    subtype: 'Primary Magical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Knowledge | <strong>Range:</strong> Very Far | <strong>Damage:</strong> d6+6 magical</p>
<p><strong><em>Powerful:</em></strong> On a successful attack, roll an additional damage die and discard the lowest result.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Advanced Greatsword',
    subtype: 'Primary Physical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Melee | <strong>Damage:</strong> d10+9 physical</p>
<p><strong><em>Massive:</em></strong> -1 to Evasion; on a successful attack, roll an additional damage die and discard the lowest result.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Advanced Halberd',
    subtype: 'Primary Physical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Very Close | <strong>Damage:</strong> d10+8 physical</p>
<p><strong><em>Cumbersome:</em></strong> -1 to Finesse</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Advanced Hallowed Axe',
    subtype: 'Primary Magical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Melee | <strong>Damage:</strong> d8+7 magical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Advanced Hand Crossbow',
    subtype: 'Secondary Physical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Finesse | <strong>Range:</strong> Far | <strong>Damage:</strong> d6+5 physical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Advanced Hand Runes',
    subtype: 'Primary Magical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Instinct | <strong>Range:</strong> Very Close | <strong>Damage:</strong> d10+6 magical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Advanced Longbow',
    subtype: 'Primary Physical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Agility | <strong>Range:</strong> Very Far | <strong>Damage:</strong> d8+9 physical</p>
<p><strong><em>Cumbersome:</em></strong> -1 to Finesse</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Advanced Longsword',
    subtype: 'Primary Physical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Agility | <strong>Range:</strong> Melee | <strong>Damage:</strong> d10+9 physical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Advanced Mace',
    subtype: 'Primary Physical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Melee | <strong>Damage:</strong> d8+7 physical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Advanced Quarterstaff',
    subtype: 'Primary Physical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Instinct | <strong>Range:</strong> Melee | <strong>Damage:</strong> d10+9 physical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Advanced Rapier',
    subtype: 'Primary Physical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Presence | <strong>Range:</strong> Melee | <strong>Damage:</strong> d8+6 physical</p>
<p><strong><em>Quick:</em></strong> When you make an attack, you can mark a Stress to target another creature within range.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Advanced Returning Blade',
    subtype: 'Primary Magical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Finesse | <strong>Range:</strong> Close | <strong>Damage:</strong> d8+6 magical</p>
<p><strong><em>Returning:</em></strong> When this weapon is thrown within its range, it appears in your hand immediately after the attack.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Advanced Round Shield',
    subtype: 'Secondary Physical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Melee | <strong>Damage:</strong> d4+4 physical</p>
<p><strong><em>Protective:</em></strong> +3 to Armor Score</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Advanced Scepter',
    subtype: 'Primary Magical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Presence | <strong>Range:</strong> Far | <strong>Damage:</strong> d6+6 magical</p>
<p><strong><em>Versatile:</em></strong> This weapon can also be used with these statistics—Presence, Melee, d8+4.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Advanced Shortbow',
    subtype: 'Primary Physical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Agility | <strong>Range:</strong> Far | <strong>Damage:</strong> d6+9 physical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Advanced Shortstaff',
    subtype: 'Primary Magical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Instinct | <strong>Range:</strong> Close | <strong>Damage:</strong> d8+7 magical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Advanced Shortsword',
    subtype: 'Secondary Physical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Agility | <strong>Range:</strong> Melee | <strong>Damage:</strong> d8+4 physical</p>
<p><strong><em>Paired:</em></strong> +4 to primary weapon damage to targets within Melee range</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Advanced Small Dagger',
    subtype: 'Secondary Physical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Finesse | <strong>Range:</strong> Melee | <strong>Damage:</strong> d8+4 physical</p>
<p><strong><em>Paired:</em></strong> +4 to primary weapon damage to targets within Melee range</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Advanced Spear',
    subtype: 'Primary Physical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Finesse | <strong>Range:</strong> Very Close | <strong>Damage:</strong> d8+9 physical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Advanced Tower Shield',
    subtype: 'Secondary Physical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Melee | <strong>Damage:</strong> d6+4 physical</p>
<p><strong><em>Barrier:</em></strong> +4 to Armor Score; -1 to Evasion</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Advanced Wand',
    subtype: 'Primary Magical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Knowledge | <strong>Range:</strong> Far | <strong>Damage:</strong> d6+7 magical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Advanced Warhammer',
    subtype: 'Primary Physical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Melee | <strong>Damage:</strong> d12+9 physical</p>
<p><strong><em>Heavy:</em></strong> -1 to Evasion</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Advanced Whip',
    subtype: 'Secondary Physical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Presence | <strong>Range:</strong> Very Close | <strong>Damage:</strong> d6+4 physical</p>
<p><strong><em>Startling:</em></strong> Mark a Stress to crack the whip and force all adversaries within Melee range back to Close range.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Axe of Fortunis',
    subtype: 'Primary Magical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Melee | <strong>Damage:</strong> d10+8 magical</p>
<p><strong><em>Lucky:</em></strong> On a failed attack, you can mark a Stress to reroll your attack.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Black Powder Revolver',
    subtype: 'Primary Physical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Finesse | <strong>Range:</strong> Far | <strong>Damage:</strong> d6+8 physical</p>
<p><strong><em>Reloading:</em></strong> After you make an attack, roll a d6. On a result of 1, you must mark a Stress to reload this weapon before you can fire it again.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Blessed Anlace',
    subtype: 'Primary Magical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Instinct | <strong>Range:</strong> Melee | <strong>Damage:</strong> d10+6 magical</p>
<p><strong><em>Healing:</em></strong> During downtime, automatically clear a Hit Point.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Bravesword',
    subtype: 'Primary Physical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Melee | <strong>Damage:</strong> d12+7 physical</p>
<p><strong><em>Brave:</em></strong> -1 to Evasion; +3 to Severe damage threshold</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Buckler',
    subtype: 'Secondary Physical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Agility | <strong>Range:</strong> Melee | <strong>Damage:</strong> d4+4 physical</p>
<p><strong><em>Deflecting:</em></strong> When you are attacked, you can mark an Armor Slot to gain a bonus to your Evasion equal to your available Armor Score against the attack.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Double Flail',
    subtype: 'Primary Physical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Agility | <strong>Range:</strong> Very Close | <strong>Damage:</strong> d10+8 physical</p>
<p><strong><em>Powerful:</em></strong> On a successful attack, roll an additional damage die and discard the lowest result.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Firestaff',
    subtype: 'Primary Magical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Instinct | <strong>Range:</strong> Far | <strong>Damage:</strong> d6+7 magical</p>
<p><strong><em>Burning:</em></strong> When you roll a 6 on a damage die, the target must mark a Stress.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Flickerfly Blade',
    subtype: 'Primary Physical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Agility | <strong>Range:</strong> Melee | <strong>Damage:</strong> d8+5 physical</p>
<p><strong><em>Sharpwing:</em></strong> Gain a bonus to your damage rolls equal to your Agility.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Ghostblade',
    subtype: 'Primary Magical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Presence | <strong>Range:</strong> Melee | <strong>Damage:</strong> d10+7 phy or magical</p>
<p><strong><em>Otherworldly:</em></strong> On a successful attack, you can deal physical or magic damage.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Gilded Bow',
    subtype: 'Primary Magical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Finesse | <strong>Range:</strong> Far | <strong>Damage:</strong> d6+7 magical</p>
<p><strong><em>Self-Correcting:</em></strong> When you roll a 1 on a damage die, it deals 6 damage instead.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Hammer of Wrath',
    subtype: 'Primary Physical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Melee | <strong>Damage:</strong> d10+7 physical</p>
<p><strong><em>Devastating:</em></strong> Before you make an attack roll, you can mark a Stress to use a d20 as your damage die.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Hand Sling',
    subtype: 'Secondary Physical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Finesse | <strong>Range:</strong> Very Far | <strong>Damage:</strong> d6+4 physical</p>
<p><strong><em>Versatile:</em></strong> This weapon can also be used with these statistics—Finesse, Close, d8+4.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: "Ilmari's Rifle",
    subtype: 'Primary Magical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Finesse | <strong>Range:</strong> Very Far | <strong>Damage:</strong> d6+6 magical</p>
<p><strong><em>Reloading:</em></strong> After you make an attack, roll a d6. On a result of 1, you must mark a Stress to reload this weapon before you can fire it again.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Labrys Axe',
    subtype: 'Primary Physical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Melee | <strong>Damage:</strong> d10+7 physical</p>
<p><strong><em>Protective:</em></strong> +1 to Armor Score</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Mage Orb',
    subtype: 'Primary Magical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Knowledge | <strong>Range:</strong> Far | <strong>Damage:</strong> d6+7 magical</p>
<p><strong><em>Powerful:</em></strong> On a successful attack, roll an additional damage die and discard the lowest result.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Meridian Cutlass',
    subtype: 'Primary Physical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Presence | <strong>Range:</strong> Melee | <strong>Damage:</strong> d10+5 physical</p>
<p><strong><em>Dueling:</em></strong> When there are no other creatures within Close range of the target, gain advantage on your attack roll against them.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Powered Gauntlet',
    subtype: 'Secondary Physical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Knowledge | <strong>Range:</strong> Close | <strong>Damage:</strong> d6+4 physical</p>
<p><strong><em>Charged:</em></strong> Mark a Stress to gain a +1 bonus to your Proficiency on a primary weapon attack.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Retractable Saber',
    subtype: 'Primary Physical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Presence | <strong>Range:</strong> Melee | <strong>Damage:</strong> d10+7 physical</p>
<p><strong><em>Retractable:</em></strong> The blade can be hidden in the hilt to avoid detection.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Runes of Ruination',
    subtype: 'Primary Magical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Knowledge | <strong>Range:</strong> Very Close | <strong>Damage:</strong> d20+4 magical</p>
<p><strong><em>Painful:</em></strong> Each time you make a successful attack, you must mark a Stress.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Spiked Bow',
    subtype: 'Primary Physical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Agility | <strong>Range:</strong> Very Far | <strong>Damage:</strong> d6+7 physical</p>
<p><strong><em>Versatile:</em></strong> This weapon can also be used with these statistics—Agility, Melee, d10+5.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Talon Blades',
    subtype: 'Primary Physical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Finesse | <strong>Range:</strong> Close | <strong>Damage:</strong> d10+7 physical</p>
<p><strong><em>Brutal:</em></strong> When you roll the maximum value on a damage die, roll an additional damage die.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Widogast Pendant',
    subtype: 'Primary Magical Weapon',
    tier: 3,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Knowledge | <strong>Range:</strong> Close | <strong>Damage:</strong> d10+5 magical</p>
<p><strong><em>Timebending:</em></strong> You choose the target of your attack after making your attack roll.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Aantari Bow',
    subtype: 'Primary Physical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Finesse | <strong>Range:</strong> Far | <strong>Damage:</strong> d6+11 physical</p>
<p><strong><em>Reliable:</em></strong> +1 to attack rolls</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Bloodstaff',
    subtype: 'Primary Magical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Instinct | <strong>Range:</strong> Far | <strong>Damage:</strong> d20+7 magical</p>
<p><strong><em>Painful:</em></strong> Each time you make a successful attack, you must mark a Stress.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Braveshield',
    subtype: 'Secondary Physical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Agility | <strong>Range:</strong> Melee | <strong>Damage:</strong> d4+6 physical</p>
<p><strong><em>Sheltering:</em></strong> When you mark an Armor Slot, it reduces damage for you and all allies within Melee range of you who took the same damage.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Curved Dagger',
    subtype: 'Primary Physical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Finesse | <strong>Range:</strong> Melee | <strong>Damage:</strong> d8+9 physical</p>
<p><strong><em>Serrated:</em></strong> When you roll a 1 on a damage die, it deals 8 damage instead.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Dual-Ended Sword',
    subtype: 'Primary Physical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Agility | <strong>Range:</strong> Melee | <strong>Damage:</strong> d10+9 physical</p>
<p><strong><em>Quick:</em></strong> When you make an attack, you can mark a Stress to target another creature within range.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Extended Polearm',
    subtype: 'Primary Physical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Finesse | <strong>Range:</strong> Very Close | <strong>Damage:</strong> d8+10 physical</p>
<p><strong><em>Long:</em></strong> This weapon's attack targets all adversaries in a line within range.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Floating Bladeshards',
    subtype: 'Primary Magical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Instinct | <strong>Range:</strong> Close | <strong>Damage:</strong> d8+9 magical</p>
<p><strong><em>Powerful:</em></strong> On a successful attack, roll an additional damage die and discard the lowest result.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Fusion Gloves',
    subtype: 'Primary Magical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Knowledge | <strong>Range:</strong> Very Far | <strong>Damage:</strong> d6+9 magical</p>
<p><strong><em>Bonded:</em></strong> Gain a bonus to your damage rolls equal to your level.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Hand Cannon',
    subtype: 'Primary Physical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Finesse | <strong>Range:</strong> Very Far | <strong>Damage:</strong> d6+12 physical</p>
<p><strong><em>Reloading:</em></strong> After you make an attack, roll a d6. On a 1, you must mark a Stress to reload this weapon before you can fire it again.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Impact Gauntlet',
    subtype: 'Primary Physical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Melee | <strong>Damage:</strong> d10+11 physical</p>
<p><strong><em>Concussive:</em></strong> On a successful attack, you can spend a Hope to knock the target back to Far range.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Knuckle Claws',
    subtype: 'Secondary Physical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Melee | <strong>Damage:</strong> d6+8 physical</p>
<p><strong><em>Doubled Up:</em></strong> When you make an attack with your primary weapon, you can deal damage to another target within Melee range.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Legendary Arcane Gauntlets',
    subtype: 'Primary Magical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Melee | <strong>Damage:</strong> d10+12 magical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Legendary Battleaxe',
    subtype: 'Primary Physical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Melee | <strong>Damage:</strong> d10+12 physical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Legendary Broadsword',
    subtype: 'Primary Physical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Agility | <strong>Range:</strong> Melee | <strong>Damage:</strong> d8+9 physical</p>
<p><strong><em>Reliable:</em></strong> +1 to attack rolls</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Legendary Crossbow',
    subtype: 'Primary Physical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Finesse | <strong>Range:</strong> Far | <strong>Damage:</strong> d6+10 physical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Legendary Cutlass',
    subtype: 'Primary Physical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Presence | <strong>Range:</strong> Melee | <strong>Damage:</strong> d8+10 physical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Legendary Dagger',
    subtype: 'Primary Physical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Finesse | <strong>Range:</strong> Melee | <strong>Damage:</strong> d8+9 physical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Legendary Dualstaff',
    subtype: 'Primary Magical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Instinct | <strong>Range:</strong> Far | <strong>Damage:</strong> d8+12 magical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Legendary Glowing Rings',
    subtype: 'Primary Magical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Agility | <strong>Range:</strong> Very Close | <strong>Damage:</strong> d10+11 magical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Legendary Grappler',
    subtype: 'Secondary Physical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Finesse | <strong>Range:</strong> Close | <strong>Damage:</strong> d6+6 physical</p>
<p><strong><em>Hooked:</em></strong> On a successful attack, you can pull the target into Melee range.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Legendary Greatstaff',
    subtype: 'Primary Magical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Knowledge | <strong>Range:</strong> Very Far | <strong>Damage:</strong> d6+9 magical</p>
<p><strong><em>Powerful:</em></strong> On a successful attack, roll an additional damage die and discard the lowest result.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Legendary Greatsword',
    subtype: 'Primary Physical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Melee | <strong>Damage:</strong> d10+12 physical</p>
<p><strong><em>Massive:</em></strong> -1 to Evasion; on a successful attack, roll an additional damage die and discard the lowest result.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Legendary Halberd',
    subtype: 'Primary Physical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Very Close | <strong>Damage:</strong> d10+11 physical</p>
<p><strong><em>Cumbersome:</em></strong> -1 to Finesse</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Legendary Hallowed Axe',
    subtype: 'Primary Magical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Melee | <strong>Damage:</strong> d8+10 magical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Legendary Hand Crossbow',
    subtype: 'Secondary Physical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Finesse | <strong>Range:</strong> Far | <strong>Damage:</strong> d6+7 physical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Legendary Hand Runes',
    subtype: 'Primary Magical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Instinct | <strong>Range:</strong> Very Close | <strong>Damage:</strong> d10+9 magical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Legendary Longbow',
    subtype: 'Primary Physical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Agility | <strong>Range:</strong> Very Far | <strong>Damage:</strong> d8+12 physical</p>
<p><strong><em>Cumbersome:</em></strong> -1 to Finesse</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Legendary Longsword',
    subtype: 'Primary Physical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Agility | <strong>Range:</strong> Melee | <strong>Damage:</strong> d10+12 physical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Legendary Mace',
    subtype: 'Primary Physical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Melee | <strong>Damage:</strong> d8+10 physical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Legendary Quarterstaff',
    subtype: 'Primary Physical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Instinct | <strong>Range:</strong> Melee | <strong>Damage:</strong> d10+12 physical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Legendary Rapier',
    subtype: 'Primary Physical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Presence | <strong>Range:</strong> Melee | <strong>Damage:</strong> d8+9 physical</p>
<p><strong><em>Quick:</em></strong> When you make an attack, you can mark a Stress to target another creature within range.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Legendary Returning Blade',
    subtype: 'Primary Magical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Finesse | <strong>Range:</strong> Close | <strong>Damage:</strong> d8+9 magical</p>
<p><strong><em>Returning:</em></strong> When this weapon is thrown within its range, it appears in your hand immediately after the attack.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Legendary Round Shield',
    subtype: 'Secondary Physical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Melee | <strong>Damage:</strong> d4+6 physical</p>
<p><strong><em>Protective:</em></strong> +4 to Armor Score</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Legendary Scepter',
    subtype: 'Primary Magical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Presence | <strong>Range:</strong> Far | <strong>Damage:</strong> d6+9 magical</p>
<p><strong><em>Versatile:</em></strong> This weapon can also be used with these statistics—Presence, Melee, d8+6.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Legendary Shortbow',
    subtype: 'Primary Physical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Agility | <strong>Range:</strong> Far | <strong>Damage:</strong> d6+12 physical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Legendary Shortstaff',
    subtype: 'Primary Magical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Instinct | <strong>Range:</strong> Close | <strong>Damage:</strong> d8+10 magical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Legendary Shortsword',
    subtype: 'Secondary Physical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Agility | <strong>Range:</strong> Melee | <strong>Damage:</strong> d8+6 physical</p>
<p><strong><em>Paired:</em></strong> +5 to primary weapon damage to targets within Melee range</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Legendary Small Dagger',
    subtype: 'Secondary Physical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Finesse | <strong>Range:</strong> Melee | <strong>Damage:</strong> d8+6 physical</p>
<p><strong><em>Paired:</em></strong> +5 to primary weapon damage to targets within Melee range</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Legendary Spear',
    subtype: 'Primary Physical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Finesse | <strong>Range:</strong> Very Close | <strong>Damage:</strong> d8+12 physical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Legendary Tower Shield',
    subtype: 'Secondary Physical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Melee | <strong>Damage:</strong> d6+6 physical</p>
<p><strong><em>Barrier:</em></strong> +5 to Armor Score; -1 to Evasion.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Legendary Wand',
    subtype: 'Primary Magical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Knowledge | <strong>Range:</strong> Far | <strong>Damage:</strong> d6+10 magical</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Legendary Warhammer',
    subtype: 'Primary Physical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Melee | <strong>Damage:</strong> d12+12 physical</p>
<p><strong><em>Heavy:</em></strong> -1 to Evasion</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Legendary Whip',
    subtype: 'Secondary Physical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Presence | <strong>Range:</strong> Very Close | <strong>Damage:</strong> d6+6 physical</p>
<p><strong><em>Startling:</em></strong> Mark a Stress to crack the whip and force all adversaries within Melee range back to Close range.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Magus Revolver',
    subtype: 'Primary Magical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Finesse | <strong>Range:</strong> Very Far | <strong>Damage:</strong> d6+13 magical</p>
<p><strong><em>Reloading:</em></strong> After you make an attack, roll a d6. On a result of 1, you must mark a Stress to reload this weapon before you can fire it again.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Midas Scythe',
    subtype: 'Primary Magical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Knowledge | <strong>Range:</strong> Melee | <strong>Damage:</strong> d10+9 magical</p>
<p><strong><em>Greedy:</em></strong> Spend a handful of gold to gain a +1 bonus to your Proficiency on a damage roll.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Primer Shard',
    subtype: 'Secondary Physical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Instinct | <strong>Range:</strong> Very Close | <strong>Damage:</strong> d4 physical</p>
<p><strong><em>Locked On:</em></strong> On a successful attack, your next attack against the same target with your primary weapon automatically succeeds.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Ricochet Axes',
    subtype: 'Primary Physical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Agility | <strong>Range:</strong> Far | <strong>Damage:</strong> d6+11 physical</p>
<p><strong><em>Bouncing:</em></strong> Mark 1 or more Stress to hit that many targets in range of the attack.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Siphoning Gauntlets',
    subtype: 'Primary Magical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Presence | <strong>Range:</strong> Melee | <strong>Damage:</strong> d10+9 magical</p>
<p><strong><em>Lifestealing:</em></strong> On a successful attack, roll a d6. On a result of 6, clear a Hit Point or clear a Stress.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Sledge Axe',
    subtype: 'Primary Physical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Melee | <strong>Damage:</strong> d12+13 physical</p>
<p><strong><em>Destructive:</em></strong> -1 to Agility; on a successful attack, all adversaries within Very Close range must mark a Stress.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Swinging Ropeblade',
    subtype: 'Primary Physical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Presence | <strong>Range:</strong> Close | <strong>Damage:</strong> d8+9 physical</p>
<p><strong><em>Grappling:</em></strong> On a successful attack, you can spend a Hope to Restrain the target or pull them into Melee range with you.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Sword of Light & Flame',
    subtype: 'Primary Magical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Strength | <strong>Range:</strong> Melee | <strong>Damage:</strong> d10+11 magical</p>
<p><strong><em>Hot:</em></strong> This weapon cuts through solid material.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Thistlebow',
    subtype: 'Primary Magical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 2,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Instinct | <strong>Range:</strong> Far | <strong>Damage:</strong> d6+13 magical</p>
<p><strong><em>Reliable:</em></strong> +1 to attack rolls</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
  {
    type: 'equipment',
    name: 'Wand of Essek',
    subtype: 'Primary Magical Weapon',
    tier: 4,
    tierEnabled: true,
    hands: 1,
    handsEnabled: true,
    text: `<p><strong>Trait:</strong> Knowledge | <strong>Range:</strong> Far | <strong>Damage:</strong> d8+13 magical</p>
<p><strong><em>Timebending:</em></strong> You can choose the target of your attack after making your attack roll.</p>`,
    credits: 'Daggerheart™ Compatible. Terms at Daggerheart.com',
  },
];
