// This file is auto-generated by scripts/sync-void.ts
// Source: daggerheart-data/the_void/ancestries.json

import type { CardDetails } from '@/lib/types';

export const voidAncestries: CardDetails[] = [
  {
    type: 'ancestry',
    name: 'Earthkin',
    credits: 'The Void',
    text: `<p><em>Earthkin are descended from earth elementals. They are humanoids whose bodies are a combination of flesh and earth.</em></p><p><strong><em>Stoneskin:</em></strong> Gain a +1 bonus to your Armor Score and Damage Thresholds.</p><p><strong><em>Immoveable:</em></strong> While your feet are touching the ground, you cannot be lifted or moved against your will.</p>`,
  },
  {
    type: 'ancestry',
    name: 'Skykin',
    credits: 'The Void',
    text: `<p><em>Skykin are descended from air elementals. They are humanoids whose bodies are a combination of flesh and air.</em></p><p><strong><em>Gale Force:</em></strong> Mark a Stress to conjure a gust of wind that carries you or an ally up to Very Far range. Additionally, you can always control the speed at which you fall.</p><p><strong><em>Eye of the Storm:</em></strong> Spend 2 Hope to grant a +1 bonus to either your or an ally's Evasion until you next take Severe damage or you use Eye of the Storm again.</p>`,
  },
  {
    type: 'ancestry',
    name: 'Tidekin',
    credits: 'The Void',
    text: `<p><em>Tidekin are descended from water elementals. They are humanoids whose bodies are a combination of flesh and water.</em></p><p><strong><em>Amphibious:</em></strong> You can breathe and move naturally underwater.</p><p><strong><em>Lifespring:</em></strong> Once per rest, when you have access to a small amount of water, you can mark 2 Stress to heal a Hit Point on yourself or an ally.</p>`,
  },
  {
    type: 'ancestry',
    name: 'Emberkin',
    credits: 'The Void',
    text: `<p><em>Emberkin are descended from fire elementals. They are humanoids whose bodies are a combination of flesh and fire.</em></p><p><strong><em>Fireproof:</em></strong> You are immune to damage from magical or mundane flame.</p><p><strong><em>Ignition:</em></strong> Mark a Stress to wreathe your primary weapon in flame until the end of the scene. While ablaze, it gives off a bright light and grants a 1d6 bonus to damage rolls against targets within Melee range.</p>`,
  },
  {
    type: 'ancestry',
    name: 'Aetheris',
    credits: 'The Void',
    text: `<p><em>Aetheris are humanoids who possess radiant auras and glowing eyes. They are the descendants of celestials from the Hallows Above.</em></p><p><strong><em>Hallowed Aura:</em></strong> Once per rest, when an ally within Close range rolls with Fear, you can make it a roll with Hope instead.</p><p><strong><em>Divine Countenance:</em></strong> You have advantage on rolls to command or persuade.</p>`,
  },
  {
    type: 'ancestry',
    name: 'Gnome',
    credits: 'The Void',
    text: `<p><em>Gnomes are small humanoids most easily recognized by their dense musculature, long arms, and large facial features.</em></p><p><strong><em>Nimble Fingers:</em></strong> When you make a Finesse Roll, you can spend 2 Hope to reroll your Hope Die.</p><p><strong><em>True Sight:</em></strong> You have advantage on rolls to see through illusions.</p>`,
  },
];
