// This file is auto-generated by scripts/sync-void.ts
// Source: daggerheart-data/the_void/classes.json

import type { ClassReference } from '../types';

export const voidClasses: ClassReference[] = [
  {
    name: 'witch',
    flavor:
      'Magical practitioners who commune with the forces of nature and entities from realms beyond. Witches call forth their power through craft, rituals, incantations, herbs, stones, candles, and other tools to enact their will and conjure powerful spells.',
    domains: ['dread', 'sage'],
    startEvasion: 10,
    startHp: 6,
    items:
      'A handcrafted besom or A pouch of animal bones you found in the wild',
    features: [
      {
        name: "Witch's Charm",
        description:
          'When you or an ally within Far range rolls a failure on an action roll, you can spend 3 Hope to change it into a success with Fear instead.',
      },
      {
        name: 'Hex',
        description:
          'When a creature causes you or an ally within Close range to mark any number of Hit Points, you can mark a Stress to Hex them. Action and damage rolls against a Hexed creature gain a bonus equal to your tier. This condition lasts until the GM spends a number of Fear equal to your Spellcast trait to remove it or you Hex another creature. Otherwise, remove it when the scene ends.',
      },
      {
        name: 'Commune',
        description:
          'Once per long rest, during a moment of calm, you can commune with an ancestor, deity, nature spirit, or otherworldly being. Ask them a question, then roll a number of d6s equal to your Spellcast trait. Choose one value from the rolled results and reference the chart below for the effect:',
        extra: `<ul class="list-disc list-outside pl-4"><li>1-3: You taste a flavor, smell a scent, or feel a sensation relevant to the answer.</li><li>4-5: You hear sounds or see a vision relevant to the answer.</li><li>6: You psychically experience a scene relevant to the answer as if you were there.</li></ul>`,
      },
    ],
    questions: [],
    connections: [],
    subclasses: ['Hedge', 'Moon'],
  },
  {
    name: 'assassin',
    flavor:
      "Assassins are masters in the art of slipping past their opponents' defenses to inflict terrible pain and deadly strikes. When an assassin marks someone for death, they pursue their prey with unwavering intent.",
    domains: ['blade', 'midnight'],
    startEvasion: 12,
    startHp: 5,
    items:
      'A list of names with several marked off or A mortar and pestle inscribed with a mysterious insignia',
    features: [
      { name: 'Grim Resolve', description: 'Spend 3 Hope to clear 2 Stress.' },
      {
        name: 'Marked for Death',
        description:
          "On a successful weapon attack, you can mark a Stress to make the target Marked for Death. Attacks you make against a target that's Marked for Death gain a bonus to damage equal to +1d4 per tier. You can only have one adversary Marked for Death at a time, and can't transfer or remove the condition except by defeating the target. The GM can spend a number of Fear equal to your Proficiency to remove the Marked for Death condition. Otherwise, it ends automatically when you take a rest.",
      },
      {
        name: 'Get In & Get Out',
        description:
          'Spend a Hope to ask the GM for either a quick or inconspicuous way into or out of a building or structure you can see. The next roll you make that capitalizes on this information has advantage.',
      },
    ],
    questions: [],
    connections: [],
    subclasses: ['Executioners Guild', 'Poisoners Guild'],
  },
  {
    name: 'warlock',
    flavor:
      "Those who've traded their lives, or perhaps even their souls, to an otherworldly Patron in exchange for incredible power are known as Warlocks. Often, these mortals are at a point of desperation that leads them to such a sacrifice- to protect themselves or a loved one, aid their community, seek vengeance, increase their status, or otherwise further their ambitions.",
    domains: ['dread', 'grace'],
    startEvasion: 11,
    startHp: 5,
    items: "A carving that symbolizes your patron or A ring you can't remove",
    features: [
      {
        name: "Patron's Boon",
        description:
          'Spend 3 Hope to call out to your patron for help, gaining 1d4 Favor.',
      },
      {
        name: 'Warlock Patron',
        description:
          "You have committed yourself to a patron (god, demon, fae, or other supernatural entity) in exchange for power. Write their name above. Then choose their spheres of influence, at GM discretion (Nature & Mischief, Love & War, Knowledge & Shadow, etc.), record them below, and set their values to +2. Anytime you increase your tier, these spheres of influence gain a permanent +1 bonus. Before making an action roll that relates to one of your patron's spheres of influence, you can spend a Favor to call on them and add its value to the roll.",
      },
      {
        name: 'Favor',
        description:
          'Start with 3 Favor. During a rest, spend one of your downtime moves to tithe to your patron. When you do, gain Favor equal to your Presence. If you choose to forgo this offering, the GM instead gains a Fear.',
      },
    ],
    questions: [],
    connections: [],
    subclasses: ['Pact of the Endless', 'Pact of the Wrathful'],
  },
  {
    name: 'brawler',
    flavor:
      'Experts in unarmed combat, brawlers hone their bodies into lethal weapons using impressive physical prowess. Whether they learned in a structured school environment or picked up their skills one fight at a time, the process is always rigorous, with brawlers developing their body and mind to work as one.',
    domains: ['bone', 'valor'],
    startEvasion: 10,
    startHp: 6,
    items: 'Hand wraps from a mentor or A book about your secret hobby',
    features: [
      {
        name: 'Staggering Strike',
        description:
          'Spend 3 Hope when you succeed on an attack to temporarily Stagger your target and force them to mark a Stress. While Staggered, they have disadvantage on attack rolls.',
      },
      {
        name: 'I Am the Weapon',
        description: "While you don't have any equipped weapons:",
        extra: `<ul class="list-disc list-outside pl-4"><li>You gain a +1 bonus to Evasion.</li><li>Your unarmed strikes are considered a Melee weapon, use the trait of your choice, and deal d8+d6 phy damage using your Proficiency.</li></ul>`,
      },
      {
        name: 'Combo Strikes',
        description:
          "After making a damage roll with a Melee weapon but before dealing that damage to the target, mark a Stress to start a combo strike. When you do, roll your Combo Die and note its value. Then, roll your Combo Die again. If the value of the second roll is equal to or greater than your first roll, continue rolling until the latest Combo Die's roll is less than the roll that preceeded it. Total all rolled values and add that amount to your weapon's damage. These values cannot be adjusted by features that affect damage dice. Your Combo Die starts as a d4. When you level up, once per tier you may use one of your advancement options to increase your Combo Die instead.",
      },
    ],
    questions: [],
    connections: [],
    subclasses: ['Juggernaut', 'Martial Artist'],
  },
];
