// This file is auto-generated by scripts/sync-void.ts
// Source: daggerheart-data/the_void/communities.json

import type { CardDetails } from '@/lib/types';

export const voidCommunities: CardDetails[] = [
  {
    type: 'community',
    name: 'Duneborne',
    credits: 'The Void',
    text: `<p><em>Being part of a duneborne community means you've made a home among the shifting sands and arid climate of the desert.</em></p><p><strong><em>Oasis:</em></strong> During a short rest, you or an ally can reroll a die used for a downtime action.</p>`,
  },
  {
    type: 'community',
    name: 'Hearthborne',
    credits: 'The Void',
    text: `<p><em>Coming from a hearthborne community means you come from humble origins, having lived in a small village or the countryside.</em></p><p><strong><em>Close-Knit:</em></strong> Once per long rest, you can spend any number of Hope to give an ally the same number of Hope.</p>`,
  },
  {
    type: 'community',
    name: 'Freeborne',
    credits: 'The Void',
    text: `<p><em>Being part of a freeborne community means you're from a collective that lived under tyrannical rule and is now liberated.</em></p><p><strong><em>Unbound:</em></strong> Once per session, when you make an action roll with Fear, you can change it to a roll with Hope instead.</p>`,
  },
  {
    type: 'community',
    name: 'Reborne',
    credits: 'The Void',
    text: `<p><em>You were once a member of another community, but you can no longer remember it.</em></p><p><strong><em>Found Family:</em></strong> Once per session, you can spend a Hope to use an ally's community ability. When you do, your ally gains a Hope. At any point, when you've discovered the community you were once a part of, or have joined a new community, you can permanently trade this community card for that one instead.</p>`,
  },
  {
    type: 'community',
    name: 'Frostborne',
    credits: 'The Void',
    text: `<p><em>Being part of a frostborne community means you come from a place of snow and ice.</em></p><p><strong><em>Hardy:</em></strong> Once per rest, you can Help an Ally traverse difficult terrain without spending a Hope.</p>`,
  },
  {
    type: 'community',
    name: 'Warborne',
    credits: 'The Void',
    text: `<p><em>Being part of a warborne community means you come from a place that is, or was, ravaged by war.</em></p><p><strong><em>Brave Face:</em></strong> Once per session, when an attack would cause you to mark a Stress, you can spend a Hope instead.</p>`,
  },
];
