// This file is auto-generated by scripts/sync-void.ts
// Source: daggerheart-data/the_void/subclasses.json

import type { SubclassReference } from '../types';

export const voidSubclasses: SubclassReference[] = [
  {
    className: 'assassin',
    name: 'Executioners Guild',
    image: null,
    artist: '',
    description: '',
    foundation: [
      {
        name: 'First Strike',
        description:
          'The first time in a scene you succeed on an attack roll, double the damage of the attack.',
      },
      {
        name: 'Ambush',
        description: 'Your Marked for Death feature uses d6s instead of d4s.',
      },
    ],
    specialization: [
      {
        name: 'Death Strike',
        description:
          'When you deal Severe damage to a creature, you can mark a Stress to make them mark an additional Hit Point.',
      },
      {
        name: "Scorpion's Poise",
        description:
          'You gain a +2 bonus to your Evasion against any attacks made by a creature Marked for Death.',
      },
    ],
    mastery: [
      {
        name: 'True Strike',
        description:
          'Once per long rest, when you fail an attack roll, you can spend a Hope to make it a success instead.',
      },
      {
        name: 'Backstab',
        description: 'Your Marked for Death feature uses d8s instead of d6s.',
      },
    ],
  },
  {
    className: 'assassin',
    name: 'Poisoners Guild',
    image: null,
    artist: '',
    description: '',
    foundation: [
      {
        name: 'Toxic Concoctions',
        description:
          'Mark a Stress to add 1d4+1 tokens to this card. On your next long rest, clear this card. You know these poisons:',
        extra: `<ul class="list-disc list-outside pl-4"><li>Gorgon Root: The target gains a permanent -1 penalty to their Difficulty. This can only affect them once.</li><li>Grave Spore: The target must also mark a Stress.</li><li>Leech Weed: Gain a +1d6 damage bonus on this attack.</li></ul>`,
      },
      {
        name: 'Envenomate',
        description:
          "When you make a successful weapon attack, you can spend a token from this card to afflict the target with a known poison's effect.",
      },
    ],
    specialization: [
      {
        name: 'Poison Compendium',
        description: 'You also know these poisons:',
        extra: `<ul class="list-disc list-outside pl-4"><li>Midnight's Veil: The target gains a permanent -2 penalty to attack rolls. This can only affect them once.</li><li>Ghost Petal: Permanently decrease the damage dice of the target's standard attack by one step (d10 to d8, d8 to d6, etc.). This can only affect them once.</li></ul>`,
      },
      {
        name: "Adder's Blessing",
        description: 'You are immune to poisons and other toxins.',
      },
    ],
    mastery: [
      {
        name: 'Venomancer',
        description: 'You also know these poisons:',
        extra: `<ul class="list-disc list-outside pl-4"><li>Blight Seed: The target gains a permanent -3 penalty to their damage thresholds. This can only affect them once.</li><li>Fear Leaf: This attack gains a damage bonus equal to the result of your Fear Die.</li></ul>`,
      },
      {
        name: 'Twin Fang',
        description:
          "When you afflict a target with a known poison's effect, you can spend an additional token to inflict the effect of a second known poison.",
      },
    ],
  },
  {
    className: 'brawler',
    name: 'Juggernaut',
    image: null,
    artist: '',
    description: '',
    foundation: [
      {
        name: 'Powerhouse',
        description:
          'Increase the d8 damage dice for your unarmed attack to d10s. Additionally, you can mark a Stress to target two creatures within Melee range with a single attack roll.',
      },
      {
        name: 'Overwhelm',
        description:
          'On a successful attack, you can spend a Hope to force the target to mark a Stress or to throw them within Close range.',
      },
    ],
    specialization: [
      {
        name: 'Rugged',
        description:
          'Gain a permanent +3 bonus to your Severe damage threshold. Additionally, your Powerhouse feature can target up to three creatures instead of two.',
      },
      {
        name: 'Eye for an Eye',
        description:
          'When you mark more than one Hit Point from an attack in Melee range, the attacker must make a Reaction Roll (13). On a failure, once per rest, they immediately mark the same number of Hit Points in return.',
      },
    ],
    mastery: [
      {
        name: 'Pummeljoy',
        description:
          'When you critically succeed on a weapon attack in Melee range, you gain an additional Hope, clear an additional Stress, and gain a +1 bonus to your Proficiency for the attack.',
      },
      {
        name: 'Not Done Yet',
        description:
          'When you mark more than one HP from an attack, you can gain a Hope or clear a Stress.',
      },
    ],
  },
  {
    className: 'brawler',
    name: 'Martial Artist',
    image: null,
    artist: '',
    description: '',
    foundation: [
      {
        name: 'Martial Form',
        description:
          'Take the Martial Form sheet. You start with two martial stances from Tier 1. When you reach a new tier, take two additional stances at your tier or lower.',
      },
      {
        name: 'Focus',
        description:
          'During a rest, roll a number of d6s equal to your Instinct and place a number of Focus tokens equal to the highest value rolled on this card. Spend a Focus to shift into a stance until you take Severe damage, the scene ends, you mark your last Hit Point, or you shift into another stance.',
      },
    ],
    specialization: [
      {
        name: 'Keen Defenses',
        description:
          'When you are targeted by an attack, you can spend a Focus to give the attack roll disadvantage.',
      },
      {
        name: 'Spirit Blast',
        description:
          'Spend a Focus to make an Instinct Roll against an adversary within Close range. On a success, deal d20+3 magic damage using your Proficiency, and you can spend an additional Focus to make them temporarily Vulnerable.',
      },
    ],
    mastery: [
      {
        name: 'Limit Breaker',
        description:
          'Once per rest, you can perform an unbelievable feat such as running across water, leaping between distant rooftops, or scaling the side of a building without needing to roll. When you do, gain a Hope and clear a Stress.',
      },
    ],
  },
  {
    className: 'warlock',
    name: 'Pact of the Endless',
    image: null,
    artist: '',
    description: '',
    foundation: [
      {
        name: "Patron's Mantle",
        description:
          'Mark a Stress to cloak yourself in a terrifying aspect of your Patron that lasts until you take Severe damage or the scene ends:',
        extra: `<ul class="list-disc list-outside pl-4"><li>When you would mark an Armor Slot, you can spend 2 Favor instead.</li><li>You gain a bonus equal to your tier on action rolls to intimidate a target.</li></ul>`,
      },
      {
        name: 'Deadly Devotion',
        description:
          'On a successful attack, you can spend a Favor to gain a +1 bonus to your Evasion until you mark a Hit Point or take a rest.',
      },
    ],
    specialization: [
      {
        name: 'Draining Invocation',
        description:
          'When an adversary attacks you or an ally within Very Close range, you can spend a Favor to make them use a d12 instead of a d20 for the attack roll. Additionally, the adversary must mark a Stress, and you can clear a Stress.',
      },
    ],
    mastery: [
      {
        name: 'Dark Aegis',
        description:
          'Once per long rest, when you would mark any number of Hit Points, you can spend a Favor instead.',
      },
      {
        name: 'Draining Bane',
        description:
          'When an adversary attacks you or an ally within Very Close range, you can spend 2 Favor to temporarily Drain them. When you do, they must mark a Stress and you can clear a Stress. A Drained creature uses a d12 instead of a d20 for attack rolls.',
      },
    ],
  },
  {
    className: 'warlock',
    name: 'Pact of the Wrathful',
    image: null,
    artist: '',
    description: '',
    foundation: [
      {
        name: 'Favored Weapon',
        description:
          "Mark a Stress to imbue your weapon with your Patron's fury until you deal Severe damage. On a successful imbued weapon attack, you can spend any number of Favor to gain a +1d6 damage bonus for each Favor spent.",
      },
      {
        name: 'Herald of Death',
        description:
          'When you fail an attack roll, you can spend a Favor to reroll it. If it fails again, mark a Stress and take the new result.',
      },
    ],
    specialization: [
      {
        name: 'Menacing Reach',
        description:
          "When you imbue your weapon with your Patron's fury, you can mark an additional Stress to increase its range by one step (Melee to Very Close, Very Close to Close, etc.).",
      },
      {
        name: 'Diminish MyFoes',
        description:
          'When you succeed with Hope on an action roll against a target, you can spend a Hope to make your target mark a Stress.',
      },
    ],
    mastery: [
      {
        name: 'Fearsome Attack',
        description:
          "You can always spend a Favor to reroll any number of your damage dice. You can continue spending Favor to reroll the same dice as many times as you'd like.",
      },
      {
        name: 'Divine Ire',
        description:
          'Once per rest, when you take damage, you can spend any number of Favor to target that many adversaries within Close range. Each target must mark a Hit Point.',
      },
    ],
  },
  {
    className: 'witch',
    name: 'Hedge',
    image: null,
    artist: '',
    description: '',
    foundation: [
      {
        name: 'Herbal Remedies',
        description:
          'When you or an ally clear one or more Hit Points or Stress as the result of using a consumable, increase the number cleared by one.',
      },
      {
        name: 'Tethered Talisman',
        description:
          "Once per rest, you can imbue a small item with your protective essence. When the person holding the talisman takes damage, you can expend its magic to reduce the number of Hit Points they mark by one. You can't create a new talisman until the old one has been used.",
      },
    ],
    specialization: [
      {
        name: 'Walk Between Worlds',
        description:
          'Make a Spellcast Roll (13) to step beyond the veil of death and converse with any nearby spirits. Place a number of tokens equal to your Spellcast trait on this card and remove one each time a spirit answers a question. You return to the mortal realm when the last token is removed.',
      },
      {
        name: 'Enhanced Hex',
        description:
          'Attacks you make against Hexed creatures gain a damage bonus equal to your Proficiency.',
      },
    ],
    mastery: [
      {
        name: 'Circle of Power',
        description:
          'Once per rest, mark a circle on the ground around you up to Very Close range and place a number of tokens equal to your Spellcast Trait on this card. Each time you or any ally within the circle makes an action roll or is hit with an attack, remove a token. This spell lasts until the last token is removed or you step out of the circle. While within this circle, you and any allies:',
        extra: `<ul class="list-disc list-outside pl-4"><li>Gain a +4 bonus to your damage thresholds.</li><li>Gain a +2 bonus to your attack rolls.</li><li>Gain a +1 bonus to your Evasion.</li></ul>`,
      },
    ],
  },
  {
    className: 'witch',
    name: 'Moon',
    image: null,
    artist: '',
    description: '',
    foundation: [
      {
        name: "Night's Glamour",
        description:
          'Mark a Stress to Glamour yourself in a magical facade that lasts until you mark a Hit Point, make an attack, or take a rest. While Glamoured, you can:',
        extra: `<ul class="list-disc list-outside pl-4"><li>Disguise yourself to look like any creature of your approximate size that you've seen.</li><li>Enhance your own appearance. You gain advantage on Presence Rolls that leverage this change.</li></ul>`,
      },
    ],
    specialization: [
      {
        name: 'Moonbeam',
        description:
          'Once per session, you can conjure a column of moonlight that illuminates the area within Close range until the end of the scene. While bathed in this moonlight, you and any allies gain a +1 bonus to Spellcast Rolls and advantage on rolls to see through illusions.',
      },
      {
        name: 'Ire of Pale Light',
        description:
          'When a Hexed creature within Far range fails an attack roll, they must mark a Stress.',
      },
    ],
    mastery: [
      {
        name: 'Lunar Phases',
        description:
          'Your spirit ebbs and flows like the phases of the moon. At the beginning of each session, roll a d4 and gain the matching effect until the end of the session:',
        extra: `<ul class="list-disc list-outside pl-4"><li>1: New - You can always spend a Hope to reduce Minor damage to None.</li><li>2: Waxing - Gain a +2 bonus to your damage rolls.</li><li>3: Full - Gain a +2 bonus to your damage thresholds.</li><li>4: Waning - Gain a +1 bonus to your Evasion.</li></ul>`,
      },
    ],
  },
];
