// This file is auto-generated by scripts/sync-void.ts
// Source: daggerheart-data/the_void/transformations.json

import type { CardDetails } from '@/lib/types';

export const voidTransformations: CardDetails[] = [
  {
    type: 'transformation',
    name: 'Vampire',
    credits: 'The Void',
    text: `<p><em>Vampires are undead, fanged creatures that drink the blood of the living.</em></p><p><strong><em>Fangs:</em></strong> Make a Strength Roll to bite a target within Melee range, dealing d8 physical damage using your Proficiency.</p><p><strong><em>Feed:</em></strong> On a successful Fangs attack against a living creature, you can mark a Stress to Feed. Place a number of tokens on this card equal to the number of Hit Points your target marks. You can hold up to 5 tokens at a time. Spend a token before an action roll to make your Fear Die a d20 instead. When you take a Long Rest, remove a token. If there are no tokens on this card, all your action and reaction rolls are made with disadvantage.</p>`,
  },
  {
    type: 'transformation',
    name: 'Werewolf',
    credits: 'The Void',
    text: `<p><em>Werewolves are creatures who transform into supernatural wolves.</em></p><p><strong><em>Wolf Form:</em></strong> When you mark one or more Hit Points, you can also mark a Stress to enter your Wolf Form. While in this form, gain a d10 Wolf Die that you add to all attack and damage rolls. When you would gain a Hope while in Wolf Form, you mark a Stress instead.</p><p><strong><em>Frenzy:</em></strong> When you mark your last Stress while in Wolf Form, you go into a Frenzy. Roll a number of d20s equal to your tier and automatically deal that much physical damage to all creatures within Very Close range. Then drop out of Wolf Form.</p>`,
  },
  {
    type: 'transformation',
    name: 'Reanimated',
    credits: 'The Void',
    text: `<p><em>Reanimated are corpses who have been brought back to life.</em></p><p><strong><em>Stitch Up:</em></strong> During a rest, you can only clear Hit Points if you have access to remains from a recently deceased creature. Describe how using this material affects your appearance. You cannot clear Hit Points by any means except a downtime move or the Risk It All death move.</p><p><strong><em>Corpse:</em></strong> When you Risk It All on a death move, if you fail, you can permanently mark a Hit Point to succeed instead. When you do, you still use the Hope Die's value to clear Hit Points and Stress.</p>`,
  },
  {
    type: 'transformation',
    name: 'Shapeshifter',
    credits: 'The Void',
    text: `<p><em>Shapeshifters are creatures that can change their physical form.</em></p><p><strong><em>Change Shape:</em></strong> During a long rest, you can spend a downtime move to swap your current ancestry with another. When you do, describe how your appearance changes.</p><p><strong><em>Only Skin Deep:</em></strong> When you Change Shape, you only gain the benefit of one of the ancestry's features, which you select when you choose the ancestry. You can spend a downtime move to switch which of your ancestry's features you gain the benefit of.</p>`,
  },
  {
    type: 'transformation',
    name: 'Ghost',
    credits: 'The Void',
    text: `<p><em>Ghosts are a spirit trapped between the mortal realm and the veil of death.</em></p><p><strong><em>Spirit Form:</em></strong> Your physical form can shift between corporeal and incorporeal. Mark a Stress to transition into and out of your Spirit Form. While in Spirit Form, you can move through solid objects, are immune to physical damage, and take double magic damage. You can spend 2 Hope to attack or physically interact with the material world.</p><p><strong><em>Ephemeral:</em></strong> Cross out a Hit Point slot when you take this card and when you increase your tier. When you mark your last Hit Point, you must choose Blaze of Glory as your death move.</p>`,
  },
  {
    type: 'transformation',
    name: 'Demigod',
    credits: 'The Void',
    text: `<p><em>Demigods are creatures whose veins flow with the blood of the gods.</em></p><p><strong><em>Ichor of the Gods:</em></strong> Your advantage die is always a d10 instead of a d6.</p><p><strong><em>Weight of Divinity:</em></strong> When you roll a failure with Fear, you must mark a Stress or give the GM an additional Fear.</p>`,
  },
];
